title: Nguyễn Ngọc Bình
description: Note interesting things.

# Development server config, needed to load some of the content
webrick:
  headers:
    Access-Control-Allow-Origin: "*"

# Theme settings
site_author: Nguyễn Ngọc Bình
repo_url: 'https://nguyenngocbinh.github.io/'
edit_on_github: true
github_docs_folder: false
sticky_navigation: true
prev_next_buttons_location: both
search_enabled: true
hljs_style: github-gist
