site_name: 'Read The Docs NguyenNgocBinh'
site_description: 'Note interesting things.'
repo_url: 'https://nguyenngocbinh.github.io/'
repo_name: 'GitHub'
docs_dir: 'docs/'
site_dir: '_site_mkdocs/'
theme: 'readthedocs'
prev_next_buttons_location: 'both'
copyright: 'Nguyen Ngoc Binh'
